# Auto-generated by prepare_profile_ref_voices.py

REFERENCE_VOICE_MAP = {
    "Wang Xiaohong": "ref_voices/wang_xiaohong.wav",
    "Li Ting": "ref_voices/li_ting.wav",
    "Wang Xiaoming": "ref_voices/wang_xiaoming.wav",
    "Liu Li": "ref_voices/liu_li.wav",
    "Zhang Wei": "ref_voices/zhang_wei.wav",
    "Zhao Ming": "ref_voices/zhao_ming.wav",
    "Zhang Wen": "ref_voices/zhang_wen.wav",
    "Li Ming": "ref_voices/li_ming.wav",
    "Chen Hua": "ref_voices/chen_hua.wav",
    "Liu Qiang": "ref_voices/liu_qiang.wav",
}
